// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountPage: typeof import('./src/views/profile/AccountPage.vue')['default']
    CartModal: typeof import('./src/components/CartModal.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    CategoryForm: typeof import('./src/partials/CategoryForm.vue')['default']
    CheckoutView: typeof import('./src/views/CheckoutView.vue')['default']
    copy: typeof import('./src/partials/CategoryForm copy.vue')['default']
    CreateView: typeof import('./src/views/CreateView.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    LandingView: typeof import('./src/views/LandingView.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MenuDetailView: typeof import('./src/views/menu/MenuDetailView.vue')['default']
    MenuListView: typeof import('./src/views/menu/MenuListView.vue')['default']
    MenuProductForm: typeof import('./src/components/MenuProductForm.vue')['default']
    MenuView: typeof import('./src/views/menu/MenuView.vue')['default']
    ModuleThing: typeof import('./src/components/ModuleThing.vue')['default']
    MyErrorView: typeof import('./src/views/MyErrorView.vue')['default']
    OptionsForm: typeof import('./src/components/OptionsForm.vue')['default']
    ProductDetailView: typeof import('./src/views/product/ProductDetailView.vue')['default']
    ProductForm: typeof import('./src/partials/ProductForm.vue')['default']
    ProductListView: typeof import('./src/views/product/ProductListView.vue')['default']
    ProfileView: typeof import('./src/views/profile/ProfileView.vue')['default']
    ReturnNav: typeof import('./src/partials/ReturnNav.vue')['default']
    RewardsView: typeof import('./src/views/RewardsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/views/SearchView.vue')['default']
    SignInBlock: typeof import('./src/components/SignInBlock.vue')['default']
    SignInView: typeof import('./src/views/SignInView.vue')['default']
    SignUpView: typeof import('./src/views/SignUpView.vue')['default']
    SiteFooter: typeof import('./src/partials/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/partials/SiteHeader.vue')['default']
    SpriteSheet: typeof import('./src/partials/SpriteSheet.vue')['default']
    SvgIcon: typeof import('./src/partials/SvgIcon.vue')['default']
  }
}
