// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartModal: typeof import('./src/components/CartModal.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MenuProductForm: typeof import('./src/components/MenuProductForm.vue')['default']
    ModuleThing: typeof import('./src/components/ModuleThing.vue')['default']
    OptionsForm: typeof import('./src/components/OptionsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInBlock: typeof import('./src/components/SignInBlock.vue')['default']
  }
}
